#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE "$DB_USERNAME";
	CREATE USER "$DB_USERNAME" WITH PASSWORD '$DB_USER_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE "$DB_USERNAME" TO "$DB_USERNAME";
	GRANT ALL PRIVILEGES ON DATABASE "$DB_NAME" TO "$DB_USERNAME";
	ALTER DATABASE "$DB_USERNAME" OWNER TO "$DB_USERNAME";
	ALTER DATABASE "$DB_NAME" OWNER TO "$DB_USERNAME";
EOSQL