version: "3.8"
services:
  api:
    container_name: fastapi-docker
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - redis
      - postgres
    volumes:
      - ./:/usr/src/app

networks:
  redis:
    name: redis_network
    external: true
  postgres:
    name: postgres_network
    external: true
